# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-27 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=90, verbose_name='题目'),
        ),
    ]
